//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoclubAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor_Pelicula
    {
        public int idActor_Pelicula { get; set; }
        public int idActor { get; set; }
        public int idPelicula { get; set; }
        public int Sueldo { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Pelicula Pelicula { get; set; }
    }
}
